---
# tasks file for docker

- name: ensure docker gpg key is added
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /etc/apt/keyrings/docker.gpg

- name: get machine architecture
  command: "dpkg --print-architecture"
  register: architecture

- name: ensure docker repository is added
  become: yes
  apt_repository:
    repo: "deb [arch={{ architecture.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    state: present
    update_cache: yes

- name: ensure docker is installed
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: ensure docker group exists
  become: yes
  group:
    name: docker
    state: present

- name: ensure user is added to docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: reset ansible connection ( for group membership to take effect )
  meta: reset_connection

- name: ensure docker is running
  become: yes
  service:
    name: docker
    state: restarted
    enabled: yes

- name: ensure docker pip module is installed
  pip:
    name: docker
    state: present
